server:
    port: 18761
 
spring:
    application:
        name: wp-proejct-eureka_discovery_server

# [참고] https://kkwonsy.tistory.com/90
# [참고] https://assu10.github.io/dev/2020/12/05/spring-cloud-eureka-configuration/
eureka:
    # 유레카 서버 관련 설정
    server:
        # 유레카에 등록된 서비스는 하트비트를 보내줌으로서 서비스가 살아있는 지 확인한다. 
        # 원래는 특정 시간안에 하트비트가 일정 횟수 들어오지 않으면 서비스가 해제된다.
        # 그런데, enable-self_preservation 설정을 false로 하면 하트비트가 들어오지 않을 시 바로 서비스 제거한다.
        # 일시적인 네트워크 장애로 인한 서비스 해제 막기 위한 자기 보호 모드 (default: true, 운영에선 true 로 설정 필요)
        enable-self-preservation: false
        # 클라이언트 하트비트 간격
        expected-client-renewal-interval-seconds: 30   
        # Eureka Server의 캐싱 업데이트 주기
        # Eureka Client 등록 시 최장 딜레이 시간 = eureka.server.response-cache-update-interval-ms (Eureka Server 의 캐싱 업데이트 주기, 30초) + eureka.client.registry-fetch-interval-seconds (서비스 목록을 캐싱할 주기, 30초) = 60초
        response-cache-update-interval-ms: 30000
        # 클라이언트로부터 하트비트가 계속 수신 되는 지 점검(default: 60000)
        eviction-interval-timer-in-ms: 10000
        renewal-percent-threshold: 0.85
        #renewal-threshold-update-interval-ms: 15
    instance:
        hostname: localhost
        # 서비스의 호스트 이름이 아닌 IP주소를 Eureka Server에 등록하도록 지정(default: false)
        # prefer-ip-address: false

        # 클라이언트가 서버로 30초(default) 마다 하트비트 전송
        # lease-renewal-interval-in-seconds: 30
        # 서버가 하트비트를 받지 못하면 90초(default)동안 하트비트가 수신되지 않으면 서비스 등록을 해지
        # 단, 유레카 인스턴스가 정상적으로 종료된 경우는 레지스트리에서 바로 제거
        # 이 설정값은 lease-renewal-interval-in-seconds 설정보다 커야함
        lease-expiration-duration-in-seconds: 90
    client:
        # euraka의 registry에 등록할지 여부를 설정(default: true)
        # 클러스터링 모드의 Eureka Server구성은 서로 peering 구성이 가능. (Eureka Server 설정에 정의된 peering 노드를 찾아서 레지스트리 정보의 sync 를 맞춤)
        # 독립 실행형 모드(standalone)에서는 peering 실패가 발생하므로 Eureka Client측 동작을 끔
        register-with-eureka: false     
        # registy에 있는 정보를 가져올지 여부를 결정
        # true 로 설정 시 검색할 때마다 Eureka Server 를 호출하는 대신 레지스트리가 로컬로 캐싱됨
        # 30초마다 Eureka Client 가 유레카 레지스트리 변경 사항 여부 재확인함
        fetch-registry: false
        # 서비스 목록을 캐싱할 주기(설정한 시간마다 캐싱)
        # registry-fetch-interval-seconds: 30
        # 캐싱 시 변경된 부분만 업데이트 할 지 여부(default: false)
        # disable-delta: false
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
